name = "my-worker"
compatibility_date = "2025-01-01"
type = "javascript"
account_id = "d77b11898f84cdae637bb1bf25d7d3c0"
main = "worker.js"
workers_dev = false
route = "https://theaura.us.kg/*"
zone_id = "66b43dea5c844f14a03661b07e329a8f"
