name: Deploy to Cloudflare Worker

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ensure Node.js version compatibility

      - name: Install Wrangler CLI
        run: npm install -g wrangler@latest

      - name: Verify `package.json` exists
        run: |
          if [ ! -f "package.json" ]; then
            echo "No package.json found. Skipping npm install."
          else
            npm install
          fi

      - name: Deploy to Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: wrangler deploy --env production
